feelinstar/urls.py
from django.contrib import admin # type: ignore
from django.urls import path, include # type: ignore
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('rooms/', include('rooms.urls')),
    path("users/", include(("users.urls", "users"), namespace="users")),
    path('', include('pages.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pages/urls.py
from django.urls import path
from . import views

app_name = 'pages'

urlpatterns = [
    path('', views.index, name='index'),  # Página principal
    path('privacy/', views.privacy, name='privacy'),  # Política de privacidad
    path('terms/', views.terms, name='terms'), # Términos y condiciones
    path('about/', views.about, name='about'),  # Página "Acerca de"
    path('feed/', views.feed, name='feed'),  # Página de feed
]

rooms/urls.py
from django.urls import path
from . import views

app_name = "rooms"

urlpatterns = [
    path("crear/", views.create_room, name="create_room"),
    path('acceder/', views.access_room, name='access_room'),  
    path('creada/<int:room_id>/', views.room_created, name='room_created'), 
]

users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from users import views

app_name = "users"

urlpatterns = [
    path('signup/', views.register, name='signup'),
    path('login/', views.login_view, name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='pages:index'), name='logout'),
    path('profile/<str:username>/', views.profile_view, name='profile'),
    path('profile/edit', views.profile_edit, name='profile_edit'),    
]

templates/partials/footer.html
{% load static %}

<!-- Footer -->
<div class="footer">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="footer-col second">
                    <h6>Links</h6>
                    <ul class="list-unstyled li-space-lg p-small">
                        <li>Importante: 
                            <a href="{% url 'pages:terms' %}">Términos y condiciones</a>, 
                            <a href="{% url 'pages:privacy' %}">Política de privacidad</a>
                        </li>
                    </ul>
                </div>
                <div class="footer-col third">
                    <span class="fa-stack">
                        <a href="#facebook">
                            <i class="fas fa-circle fa-stack-2x"></i>
                            <i class="fab fa-facebook-f fa-stack-1x"></i>
                        </a>
                    </span>
                    <span class="fa-stack">
                        <a href="#pinterest">
                            <i class="fas fa-circle fa-stack-2x"></i>
                            <i class="fab fa-pinterest-p fa-stack-1x"></i>
                        </a>
                    </span>
                    <span class="fa-stack">
                        <a href="#instagram">
                            <i class="fas fa-circle fa-stack-2x"></i>
                            <i class="fab fa-instagram fa-stack-1x"></i>
                        </a>
                    </span>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Copyright -->
<div class="copyright">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <p class="p-small">Copyright © <a href="#">Feelin' Star</a></p>
            </div>
        </div>
    </div>
</div>

templates/partials/logged_navbar.html
{% load static %}

<!-- Navigation -->
<nav class="navbar navbar-expand-lg fixed-top navbar-dark">
    <div class="container">
        
        <!-- Image Logo -->
        <a class="navbar-brand logo-image" href="{% url 'pages:feed' %}">
            <img src="{% static 'images/FS_3.png' %}" alt="Feelin' Star Logo">
        </a>  

        <div class="navbar-collapse offcanvas-collapse" id="navbar">
            <ul class="navbar-nav ml-auto">
                <!-- Inicio -->
                {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'pages:feed' %}">Inicio</a>
                </li>

                <!-- Crear nueva sala -->
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'rooms:create_room' %}">
                        <i class="fas fa-plus"></i>
                    </a>
                </li>

                <!-- Perfil -->
                <li class="nav-item">
                    <a class="nav-link " href="{% url 'users:profile' request.user.username %}">Perfil</a>
                </li>

                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:login' %}">
                            <i class="fas fa-sign-in-alt"></i> Iniciar Sesión
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:signup' %}">
                            <i class="fas fa-user-plus"></i> Registrarse
                        </a>
                    </li>
                {% endif %}
                
            </ul>
        </div>
    </div>
</nav>

templates/partials/navbar.html
{% load static %}

<!-- Navigation -->
<nav class="navbar navbar-expand-lg fixed-top navbar-dark">
    <div class="container">
        
        <!-- Image Logo -->
        <a class="navbar-brand logo-image" href="{% url 'pages:index' %}">
            <img src="{% static 'images/FS_3.png' %}" alt="Feelin' Star Logo">
        </a>  

        <div class="navbar-collapse offcanvas-collapse" id="navbar">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link page-scroll" href="{% url 'pages:index' %}">Inicio</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="dropdown01" data-toggle="dropdown">Detalles</a>
                    <div class="dropdown-menu" aria-labelledby="dropdown01">
                        <a class="dropdown-item page-scroll" href="{% url 'pages:terms' %}">Términos y condiciones</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item page-scroll" href="{% url 'pages:privacy' %}">Política de privacidad</a>
                    </div>
                </li>
                <li class="nav-item">
                    <a class="nav-link page-scroll" href="{% url 'pages:about' %}">Nosotros</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link page-scroll" href="{% url 'users:login' %}">Iniciar sesión</a>
                </li>
            </ul>
        </div>
    </div>
</nav>